### ISSUE TITLE
VE processer - #NA in item ledger entry number column 

### ISSUE THREAD

**Issue by Javismkec** [milesmfe/kec.ILEConfigExcel#1]
In the output sheet of the Value Entry processor, some of the lines are displaying #NA in the column for Item Ledger Entry Number. Could you please investigate?
see screenshot 

![image](https://github.com/user-attachments/assets/18a048d4-c5a8-4c04-9cfa-164ecddd433e)

**Comment by milesmfe** [comment]
It looks like the input data was incomplete. All ILE values present in the input data appear in the ILE No. Map - in this example the VE input data contains references to ILEs not recorded in the ILE input data.
