### ISSUE TITLE
Discerption does not appear on the output spreadsheet for both ILE and VE

### ISSUE THREAD

**Issue by Javismkec** [milesmfe/kec.ILEConfigExcel#4]
Discerption does not appear on the output spreadsheet for both ILE and VE

**Comment by milesmfe** [comment]
Can you provide an example since the description field exists on both output sheets.

**Comment by Javismkec** [comment]
![image](https://github.com/user-attachments/assets/5f718573-86be-47ed-9c21-96b7e9dd9f01)

**Comment by milesmfe** [comment]
I attempted to replicate this but on both ILE and VE the description was included.
